package com.devzb.example.dao.model;

import java.util.Date;

public class SsoUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.id
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.guid
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String guid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.username
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.name
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.phone
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.email
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.privilege
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String privilege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.gmt_created
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.gmt_modified
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.is_deleted
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.id
     *
     * @return the value of sso_user.id
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.id
     *
     * @param id the value for sso_user.id
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.guid
     *
     * @return the value of sso_user.guid
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.guid
     *
     * @param guid the value for sso_user.guid
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.username
     *
     * @return the value of sso_user.username
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.username
     *
     * @param username the value for sso_user.username
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.name
     *
     * @return the value of sso_user.name
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.name
     *
     * @param name the value for sso_user.name
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.phone
     *
     * @return the value of sso_user.phone
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.phone
     *
     * @param phone the value for sso_user.phone
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.email
     *
     * @return the value of sso_user.email
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.email
     *
     * @param email the value for sso_user.email
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.privilege
     *
     * @return the value of sso_user.privilege
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.privilege
     *
     * @param privilege the value for sso_user.privilege
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.gmt_created
     *
     * @return the value of sso_user.gmt_created
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.gmt_created
     *
     * @param gmtCreated the value for sso_user.gmt_created
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.gmt_modified
     *
     * @return the value of sso_user.gmt_modified
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.gmt_modified
     *
     * @param gmtModified the value for sso_user.gmt_modified
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.is_deleted
     *
     * @return the value of sso_user.is_deleted
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.is_deleted
     *
     * @param isDeleted the value for sso_user.is_deleted
     *
     * @mbg.generated Wed Mar 29 14:08:59 GMT+08:00 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }
}