package com.devzb.api.dao.model;

import java.util.Date;

public class KksTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.id
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.name
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.tag
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.user_id
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.type
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.gmt_created
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kks_tag.gmt_modified
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.id
     *
     * @return the value of kks_tag.id
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.id
     *
     * @param id the value for kks_tag.id
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.name
     *
     * @return the value of kks_tag.name
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.name
     *
     * @param name the value for kks_tag.name
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.tag
     *
     * @return the value of kks_tag.tag
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.tag
     *
     * @param tag the value for kks_tag.tag
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.user_id
     *
     * @return the value of kks_tag.user_id
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.user_id
     *
     * @param userId the value for kks_tag.user_id
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.type
     *
     * @return the value of kks_tag.type
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.type
     *
     * @param type the value for kks_tag.type
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.gmt_created
     *
     * @return the value of kks_tag.gmt_created
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.gmt_created
     *
     * @param gmtCreated the value for kks_tag.gmt_created
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kks_tag.gmt_modified
     *
     * @return the value of kks_tag.gmt_modified
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kks_tag.gmt_modified
     *
     * @param gmtModified the value for kks_tag.gmt_modified
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}