package com.devzb.api.dao.mapper;

import com.devzb.api.dao.model.SsoUser;
import com.devzb.api.dao.model.SsoUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SsoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    long countByExample(SsoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    int deleteByExample(SsoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    int insertSelective(SsoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    List<SsoUser> selectByExample(SsoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    SsoUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") SsoUser record, @Param("example") SsoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    int updateByExample(@Param("record") SsoUser record, @Param("example") SsoUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated Thu Mar 30 09:05:52 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(SsoUser record);
}